In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset["classification"].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
independent.shape

(399, 27)

In [10]:
dependent=dataset[['classification_yes']]

In [11]:
dependent.shape

(399, 1)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [13]:
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [15]:
x_test

array([[-0.37004136, -0.5072062 , -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.85498667,  1.03118433,  0.94028379, ..., -1.93649167,
        -0.52223297, -0.44519456],
       [ 1.03874087, -0.5072062 , -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.24753856,  1.80037959, -0.68384276, ..., -1.93649167,
        -0.52223297, -0.44519456],
       [-0.06378435, -1.27640146,  1.75234707, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.10505818, -1.27640146, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]])

In [16]:
x_train

array([[ 0.48747826,  1.80037959, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.30372406,  0.26198906, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.61504697, -0.5072062 , -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.43129276,  0.26198906, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.35006379,  0.26198906, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.06378435, -1.27640146, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]])

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid={ "kernel": ["poly"],
    "C": [0.1, 1, 10],
    "degree": [2, 3, 4],
    "gamma": ["scale", 0.01, 0.1],
    "coef0": [0.0, 0.5, 1.0]}
grid=GridSearchCV(SVC(),param_grid, refit=True, verbose=3, n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 81 candidates, totalling 405 fits

C:\ANACONDA\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'coef0': [0.0, 0.5, 1.0],
                         'degree': [2, 3, 4], 'gamma': ['scale', 0.01, 0.1],
                         'kernel': ['poly']},
             scoring='f1_weighted', verbose=3)

In [18]:
re=grid.cv_results_

In [19]:
re

{'mean_fit_time': array([0.01117253, 0.01003842, 0.00826592, 0.00676727, 0.00752802,
        0.00857072, 0.00745916, 0.00747013, 0.00763268, 0.00682158,
        0.00653811, 0.00521841, 0.00661802, 0.00610089, 0.0044559 ,
        0.00648637, 0.00530663, 0.00493002, 0.00421247, 0.00461111,
        0.00411744, 0.00384731, 0.00582204, 0.00455041, 0.00456924,
        0.00563827, 0.00482249, 0.00573087, 0.00702472, 0.0055512 ,
        0.0057445 , 0.00646548, 0.00498033, 0.00618086, 0.00759525,
        0.00622454, 0.00460153, 0.00454383, 0.00437388, 0.00452256,
        0.00573888, 0.00463696, 0.00502067, 0.00468588, 0.00546365,
        0.00453572, 0.00441685, 0.00420127, 0.00356326, 0.00421271,
        0.00380745, 0.00400791, 0.0045506 , 0.00438151, 0.00468631,
        0.00582566, 0.00549221, 0.00501189, 0.00592241, 0.0054038 ,
        0.00611591, 0.00617986, 0.00651197, 0.00436201, 0.00420399,
        0.00387516, 0.00451384, 0.00455055, 0.00451965, 0.00431337,
        0.00446992, 0.00557103, 0.00504503, 0.00497108, 0.00548711,
        0.0043766 , 0.00403595, 0.00457492, 0.00443645, 0.00386844,
        0.00446754]),
 'std_fit_time': array([0.00172605, 0.00200955, 0.00106101, 0.00054652, 0.00082569,
        0.00308512, 0.00093548, 0.00103407, 0.00135191, 0.00145044,
        0.0009694 , 0.00050659, 0.00168458, 0.00052898, 0.00035738,
        0.00136225, 0.00037871, 0.00064722, 0.00040931, 0.00060311,
        0.00046466, 0.0006572 , 0.00260288, 0.00135008, 0.00098005,
        0.00072519, 0.00037656, 0.00039184, 0.00148723, 0.00078294,
        0.00102563, 0.00148873, 0.00038692, 0.00050362, 0.0010511 ,
        0.00068661, 0.00109022, 0.00109897, 0.00069904, 0.00039721,
        0.00180092, 0.00100364, 0.0010366 , 0.0003892 , 0.00077796,
        0.00083327, 0.00077268, 0.00082694, 0.00049746, 0.00075049,
        0.00032401, 0.00076224, 0.00052937, 0.00057512, 0.00051504,
        0.00097563, 0.00078497, 0.0009481 , 0.00057177, 0.0011333 ,
        0.00039768, 0.00018697, 0.00063043, 0.00074099, 0.00044734,
        0.00028049, 0.00069021, 0.00122257, 0.00096429, 0.00043354,
        0.00123527, 0.00075547, 0.00194154, 0.00092211, 0.0017552 ,
        0.00086496, 0.00035122, 0.00129325, 0.00053362, 0.00041894,
        0.00084326]),
 'mean_score_time': array([0.01385074, 0.01263847, 0.01378388, 0.00991936, 0.01194572,
        0.01362205, 0.01113591, 0.01197138, 0.01117687, 0.01129313,
        0.01040754, 0.00966835, 0.01020513, 0.00862584, 0.00931058,
        0.00887594, 0.00917616, 0.00929871, 0.00871992, 0.00922642,
        0.00827808, 0.0078414 , 0.00890183, 0.00834084, 0.00936708,
        0.01023684, 0.00913639, 0.00925536, 0.00940752, 0.00899796,
        0.0093771 , 0.00868478, 0.00851412, 0.00915923, 0.00899272,
        0.00918107, 0.00876184, 0.00878029, 0.00961809, 0.00909052,
        0.00878882, 0.00963778, 0.00894799, 0.00927563, 0.00923772,
        0.00885797, 0.00884981, 0.00966349, 0.00905986, 0.00882993,
        0.0094852 , 0.0083744 , 0.00898204, 0.00907683, 0.0090436 ,
        0.0094656 , 0.00900388, 0.00907612, 0.00908489, 0.00868883,
        0.00882707, 0.00947256, 0.00938673, 0.00946159, 0.008951  ,
        0.00907373, 0.00918674, 0.00922031, 0.00973144, 0.01009746,
        0.00891128, 0.00963669, 0.00933752, 0.01012821, 0.00899282,
        0.00890851, 0.00894175, 0.00892386, 0.00925021, 0.00846372,
        0.00684919]),
 'std_score_time': array([2.32658299e-03, 8.88658202e-04, 2.17838809e-03, 7.18622650e-04,
        1.66708932e-03, 3.04389237e-03, 1.32544569e-03, 2.13667753e-03,
        1.92036076e-03, 1.79052017e-03, 8.25074197e-04, 8.39502863e-04,
        8.37316554e-04, 6.77595394e-04, 3.64798894e-04, 4.78073178e-04,
        6.42397288e-04, 4.68193840e-04, 8.94943446e-05, 3.08970779e-04,
        6.39873598e-04, 1.10405691e-03, 4.26534903e-04, 1.13995463e-03,
        4.33025341e-04, 8.48746267e-04, 7.35430007e-04, 4.67863410e-04,
        7.20617006e-04, 3.12966081e-04, 4.40259583e-04, 1.74932480e-04,
        2.30977941e-04, 9.41660703e-04, 3.15647233e-04, 7.30152940e-04,
        6.80211046e-04, 8.18815618e-04, 4.86287114e-04, 1.92709335e-04,
        2.41046489e-04, 9.11015884e-04, 4.87670796e-04, 1.26693811e-03,
        3.64994329e-04, 5.80045483e-04, 8.71858850e-04, 1.23086306e-03,
        7.75797811e-04, 5.68676175e-04, 1.15327758e-03, 3.42270225e-04,
        6.84482901e-04, 9.30036938e-04, 8.04567870e-04, 6.59241307e-04,
        2.92385293e-04, 7.70145406e-04, 1.99664558e-04, 2.52026622e-04,
        8.78252946e-04, 7.81642655e-04, 4.83883799e-04, 1.16970448e-03,
        5.35484677e-04, 4.04509452e-04, 5.26267417e-04, 3.42281252e-04,
        9.02255863e-04, 7.12944244e-04, 4.61348479e-04, 6.32465155e-04,
        1.02562661e-03, 1.09105924e-03, 3.30421094e-04, 2.90406161e-04,
        2.00918809e-04, 8.27509716e-04, 8.25366642e-04, 4.30856837e-04,
        4.90011065e-04]),
 'param_C': masked_array(data=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_coef0': masked_array(data=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5,
                    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
                    0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5,
                    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_degree': masked_array(data=[2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=999999),
 'param_gamma': masked_array(data=['scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale',
                    0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1,
                    'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale',
                    0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1,
                    'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale',
                    0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1,
                    'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 0.1,
   'coef0': 0.0,
   'degree': 2,
   'gamma': 'scale',
   'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}],
 'split0_test_score': array([0.48653199, 0.48653199, 0.96328363, 0.48653199, 0.48653199,
        1.        , 0.48653199, 0.48653199, 0.94510038, 0.96328363,
        1.        , 0.98156912, 1.        , 0.77184474, 1.        ,
        1.        , 0.48653199, 1.        , 0.96328363, 0.98156912,
        1.        , 0.98156912, 0.96328363, 0.98156912, 0.98156912,
        0.96328363, 0.98156912, 0.96328363, 0.48653199, 0.94510038,
        1.        , 0.48653199, 1.        , 0.90560984, 0.48653199,
        0.92697811, 1.        , 0.96328363, 0.96328363, 0.98156912,
        0.96328363, 0.98156912, 0.98156912, 0.96328363, 0.98156912,
        0.98156912, 0.98156912, 0.98156912, 0.98156912, 1.        ,
        0.96328363, 0.98156912, 0.98156912, 0.98156912, 0.94510038,
        0.96328363, 0.94510038, 1.        , 0.77184474, 0.96328363,
        0.94510038, 0.48653199, 0.90887713, 0.96328363, 0.96328363,
        0.94510038, 0.96328363, 0.96328363, 0.98156912, 0.96328363,
        0.98156912, 0.98156912, 0.96328363, 0.98156912, 0.94510038,
        0.94510038, 0.98156912, 0.96328363, 0.94510038, 0.96328363,
        0.98156912]),
 'split1_test_score': array([0.49232119, 0.50140967, 0.90616583, 0.58149146, 0.50140967,
        0.96175502, 0.49232119, 0.50140967, 0.83332289, 0.96226415,
        0.9421662 , 0.9436995 , 0.98101383, 0.65026636, 0.98101383,
        0.96175502, 0.50140967, 0.9436995 , 0.96226415, 0.96226415,
        0.98101383, 0.96226415, 0.96226415, 0.98101383, 0.96226415,
        0.96226415, 0.98101383, 0.90693476, 0.50140967, 0.90693476,
        0.96175502, 0.50140967, 0.96175502, 0.81132075, 0.50140967,
        0.83332289, 0.96226415, 0.96226415, 0.9436995 , 0.98101383,
        0.96226415, 0.96226415, 0.98101383, 0.98101383, 0.96226415,

In [20]:
format(grid.best_params_)

"{'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}"

In [21]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_coef0,param_degree,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011173,0.001726,0.013851,0.002327,0.1,0.0,2,scale,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma':...",0.486532,0.492321,0.477841,0.477841,0.477841,0.482475,0.005964,79
1,0.010038,0.002010,0.012638,0.000889,0.1,0.0,2,0.01,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma':...",0.486532,0.501410,0.477841,0.477841,0.477841,0.484293,0.009196,72
2,0.008266,0.001061,0.013784,0.002178,0.1,0.0,2,0.1,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma':...",0.963284,0.906166,0.962573,0.981031,0.869925,0.936596,0.041791,59
3,0.006767,0.000547,0.009919,0.000719,0.1,0.0,3,scale,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma':...",0.486532,0.581491,0.477841,0.477841,0.477841,0.500309,0.040730,71
4,0.007528,0.000826,0.011946,0.001667,0.1,0.0,3,0.01,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma':...",0.486532,0.501410,0.477841,0.477841,0.477841,0.484293,0.009196,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0.004036,0.000351,0.008942,0.000201,10.0,1.0,3,0.01,poly,"{'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': ...",0.981569,0.981233,1.000000,0.981031,1.000000,0.988767,0.009174,4
77,0.004575,0.001293,0.008924,0.000828,10.0,1.0,3,0.1,poly,"{'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': ...",0.963284,0.962264,1.000000,0.981217,1.000000,0.981353,0.016651,35
78,0.004436,0.000534,0.009250,0.000825,10.0,1.0,4,scale,poly,"{'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': ...",0.945100,0.962264,1.000000,1.000000,1.000000,0.981473,0.023331,33
79,0.003868,0.000419,0.008464,0.000431,10.0,1.0,4,0.01,poly,"{'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': ...",0.963284,0.981233,1.000000,0.981031,1.000000,0.985110,0.013795,15
80,0.004468,0.000843,0.006849,0.000490,10.0,1.0,4,0.1,poly,"{'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': ...",0.981569,0.962264,1.000000,1.000000,1.000000,0.988767,0.015052,4

In [23]:
grid_predictions=grid.predict(x_test)

In [24]:
grid_predictions

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [25]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [26]:
print(cm)

[[51  0]
 [ 0 82]]

In [27]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [28]:
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        82

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133