In [1]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("CKD.csv")

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [9]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [11]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [12]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes',]]

In [13]:
independent.shape

(399, 27)

In [14]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [15]:
dependent=dataset[['classification_yes']]

In [16]:
dependent.shape

(399, 1)

In [17]:
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [21]:
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
param_grid={"var_smoothing": [1e-10, 1e-9, 1e-8],
    "priors": [None, [0.7, 0.3]]}
grid=GridSearchCV(GaussianNB(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring="accuracy")
grid.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

C:\ANACONDA\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'priors': [None, [0.7, 0.3]],
                         'var_smoothing': [1e-10, 1e-09, 1e-08]},
             scoring='accuracy', verbose=3)

In [24]:
re=grid.cv_results_

In [25]:
print(re)

{'mean_fit_time': array([0.01230092, 0.01238918, 0.00900559, 0.00891008, 0.00814266,
       0.00696397]), 'std_fit_time': array([0.00157082, 0.00169217, 0.00090951, 0.00137133, 0.00061701,
       0.00105152]), 'mean_score_time': array([0.0089077 , 0.00928168, 0.00750694, 0.00770307, 0.00741277,
       0.00661974]), 'std_score_time': array([0.00094978, 0.00129447, 0.00127895, 0.00044067, 0.00100611,
       0.00050222]), 'param_priors': masked_array(data=[None, None, None, list([0.7, 0.3]), list([0.7, 0.3]),
                   list([0.7, 0.3])],
             mask=[False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_var_smoothing': masked_array(data=[1e-10, 1e-09, 1e-08, 1e-10, 1e-09, 1e-08],
             mask=[False, False, False, False, False, False],
       fill_value=1e+20), 'params': [{'priors': None, 'var_smoothing': 1e-10}, {'priors': None, 'var_smoothing': 1e-09}, {'priors': None, 'var_smoothing': 1e-08}, {'priors': [0.7, 0.3], 'var_smoothing': 1e-10}, {'priors': [0.7, 0.3], 'var_smoothing': 1e-09}, {'priors': [0.7, 0.3], 'var_smoothing': 1e-08}], 'split0_test_score': array([0.98148148, 0.98148148, 0.90740741, 0.98148148, 0.98148148,
       0.90740741]), 'split1_test_score': array([0.98113208, 0.98113208, 0.96226415, 0.98113208, 0.98113208,
       0.96226415]), 'split2_test_score': array([0.98113208, 0.98113208, 0.96226415, 0.98113208, 0.98113208,
       0.94339623]), 'split3_test_score': array([1.        , 1.        , 0.98113208, 1.        , 1.        ,
       0.98113208]), 'split4_test_score': array([0.98113208, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
       0.96226415]), 'mean_test_score': array([0.98497554, 0.98497554, 0.95883997, 0.98497554, 0.98497554,
       0.9512928 ]), 'std_test_score': array([0.00751345, 0.00751345, 0.02706523, 0.00751345, 0.00751345,
       0.02497762]), 'rank_test_score': array([1, 1, 5, 1, 1, 6], dtype=int32)}

In [26]:
format(grid.best_params_)

"{'priors': None, 'var_smoothing': 1e-10}"

In [28]:
table=pd.DataFrame.from_dict(re)

In [31]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_priors,param_var_smoothing,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012301,0.001571,0.008908,0.000950,None,1.000000e-10,"{'priors': None, 'var_smoothing': 1e-10}",0.981481,0.981132,0.981132,1.000000,0.981132,0.984976,0.007513,1
1,0.012389,0.001692,0.009282,0.001294,None,1.000000e-09,"{'priors': None, 'var_smoothing': 1e-09}",0.981481,0.981132,0.981132,1.000000,0.981132,0.984976,0.007513,1
2,0.009006,0.000910,0.007507,0.001279,None,1.000000e-08,"{'priors': None, 'var_smoothing': 1e-08}",0.907407,0.962264,0.962264,0.981132,0.981132,0.958840,0.027065,5
3,0.008910,0.001371,0.007703,0.000441,"[0.7, 0.3]",1.000000e-10,"{'priors': [0.7, 0.3], 'var_smoothing': 1e-10}",0.981481,0.981132,0.981132,1.000000,0.981132,0.984976,0.007513,1
4,0.008143,0.000617,0.007413,0.001006,"[0.7, 0.3]",1.000000e-09,"{'priors': [0.7, 0.3], 'var_smoothing': 1e-09}",0.981481,0.981132,0.981132,1.000000,0.981132,0.984976,0.007513,1
5,0.006964,0.001052,0.006620,0.000502,"[0.7, 0.3]",1.000000e-08,"{'priors': [0.7, 0.3], 'var_smoothing': 1e-08}",0.907407,0.962264,0.943396,0.981132,0.962264,0.951293,0.024978,6

In [32]:
grid_prediction=grid.predict(x_test)

In [33]:
grid_prediction

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [34]:
from sklearn.metrics import confusion_matrix
cfm=confusion_matrix(grid_prediction,y_test)

In [35]:
print(cfm)

[[51  3]
 [ 0 79]]

In [36]:
from sklearn.metrics import classification_report 
clf_report=classification_report(y_test,grid_prediction)

In [38]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133