In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [10]:
independent.shape

(399, 27)

In [11]:
dependent=dataset[['classification_yes']]

In [12]:
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [13]:
dependent.shape

(399, 1)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [15]:
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier 
param_grid={"n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt", "log2"],
    "bootstrap": [True]}
grid=GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3 , n_jobs=-1, scoring="accuracy")
grid.fit(x_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

C:\ANACONDA\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [None, 10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='accuracy', verbose=3)

In [18]:
re=grid.cv_results_

In [19]:
re

{'mean_fit_time': array([0.23990936, 0.47200432, 0.23385601, 0.46779847, 0.2347898 ,
        0.45775032, 0.222051  , 0.44768386, 0.22179832, 0.44193158,
        0.2222497 , 0.46814747, 0.23899388, 0.46186743, 0.23784442,
        0.46452255, 0.22980232, 0.4636188 , 0.23285217, 0.44693351,
        0.22416282, 0.44696202, 0.22223539, 0.44615097, 0.22498126,
        0.44350924, 0.22482109, 0.43786345, 0.22581096, 0.45933299,
        0.24010844, 0.44902525, 0.22739472, 0.44206452, 0.21855936,
        0.44601469, 0.22270579, 0.44620795, 0.22384772, 0.43877592,
        0.22539859, 0.45084295, 0.22565322, 0.45620542, 0.23604054,
        0.42799902, 0.22133684, 0.38429441]),
 'std_fit_time': array([0.00926916, 0.00503519, 0.00632078, 0.00521495, 0.00944641,
        0.00756927, 0.00286866, 0.0055655 , 0.00203504, 0.00456553,
        0.0022721 , 0.01120937, 0.01251962, 0.01216935, 0.00273284,
        0.01204092, 0.00517265, 0.01757884, 0.0121524 , 0.00577465,
        0.00312566, 0.00766101, 0.00235161, 0.00112874, 0.00105597,
        0.00531689, 0.00319333, 0.00234306, 0.00488571, 0.02130998,
        0.01785596, 0.01401985, 0.00275746, 0.00420959, 0.00295544,
        0.00777531, 0.00279418, 0.00702715, 0.00623068, 0.00497402,
        0.00416049, 0.00990656, 0.00357035, 0.01092922, 0.00821641,
        0.01160336, 0.00188477, 0.01349769]),
 'mean_score_time': array([0.01743741, 0.02722144, 0.01646199, 0.02564726, 0.01602077,
        0.02439723, 0.01580658, 0.02469735, 0.01642728, 0.02671294,
        0.01655917, 0.02467012, 0.01582298, 0.02626681, 0.01574364,
        0.02601924, 0.01699419, 0.02449484, 0.01554961, 0.02497997,
        0.01536083, 0.02514167, 0.0168345 , 0.02483406, 0.01554232,
        0.02571707, 0.01514163, 0.02666183, 0.01633177, 0.02609119,
        0.01545658, 0.0258419 , 0.01521106, 0.02419829, 0.01824112,
        0.02567868, 0.01667876, 0.02459159, 0.01634927, 0.02566152,
        0.01608438, 0.02541728, 0.01934724, 0.02449484, 0.01530981,
        0.02155552, 0.01516337, 0.01711245]),
 'std_score_time': array([0.00099115, 0.00185119, 0.00049682, 0.00203796, 0.0008546 ,
        0.00222533, 0.00074509, 0.00113532, 0.00136877, 0.00098319,
        0.0016263 , 0.00060266, 0.00049291, 0.00206584, 0.00100904,
        0.00141927, 0.00133498, 0.00126563, 0.00039092, 0.00065981,
        0.00162788, 0.00175646, 0.00117862, 0.00042776, 0.00094504,
        0.00123062, 0.00113032, 0.00322188, 0.00155238, 0.0016371 ,
        0.00049571, 0.00131764, 0.00036748, 0.00070093, 0.00251813,
        0.00185104, 0.00096218, 0.00087046, 0.00104747, 0.00123982,
        0.00053106, 0.00091709, 0.00209484, 0.00059077, 0.00048827,
        0.00365416, 0.00215746, 0.00360544]),
 'param_bootstrap': masked_array(data=[True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=True),
 'param_max_depth': masked_array(data=[None, None, None, None, None, None, None, None, None,
                    None, None, None, None, None, None, None, 10, 10, 10,
                    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                    20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'log2', 'log2', 'log2', 'log2', 'log2', 'log2',
                    'log2', 'log2', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'log2', 'log2', 'log2', 'log2',
                    'log2', 'log2', 'log2', 'log2', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'log2', 'log2',
                    'log2', 'log2', 'log2', 'log2', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
                    1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1,
                    2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_min_samples_split': masked_array(data=[2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2,
                    5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5,
                    2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_n_estimators': masked_array(data=[100, 200, 100, 200, 100, 200, 100, 200, 100, 200, 100,
                    200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200,
                    100, 200, 100, 200, 100, 200, 100, 200, 100, 200, 100,
                    200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200,
                    100, 200, 100, 200],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': None,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 10,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'sqrt',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'bootstrap': True,
   'max_depth': 20,
   'max_features': 'log2',
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200}],
 'split0_test_score': array([0.96296296, 0.98148148, 0.96296296, 1.        , 0.96296296,
        0.98148148, 0.96296296, 0.94444444, 0.98148148, 1.        ,
        1.        , 1.        , 0.98148148, 0.98148148, 0.98148148,
        1.        , 0.98148148, 1.        , 0.98148148, 0.98148148,
        0.98148148, 0.96296296, 0.96296296, 0.98148148, 1.        ,
        0.98148148, 0.98148148, 1.        , 0.98148148, 0.96296296,
        0.98148148, 1.        , 0.98148148, 0.98148148, 0.94444444,
        0.98148148, 0.96296296, 0.98148148, 0.98148148, 0.98148148,
        0.96296296, 1.        , 0.98148148, 0.98148148, 1.        ,
        0.98148148, 0.96296296, 0.98148148]),
 'split1_test_score': array([0.98113208, 0.98113208, 0.96226415, 0.98113208, 0.98113208,
        0.98113208, 0.94339623, 0.98113208, 0.96226415, 0.98113208,
        0.98113208, 0.98113208, 0.96226415, 0.98113208, 0.94339623,
        0.96226415, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.96226415, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.96226415, 0.96226415,
        0.98113208, 0.96226415, 0.98113208, 0.96226415, 0.98113208,
        0.96226415, 0.98113208, 0.98113208, 0.94339623, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.98113208, 0.96226415,
        0.98113208, 0.96226415, 0.94339623]),
 'split2_test_score': array([0.98113208, 0.98113208, 0.96226415, 0.98113208, 0.9245283 ,
        0.94339623, 0.96226415, 0.94339623, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.96226415, 0.96226415, 0.9245283 ,
        0.94339623, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.94339623, 0.96226415, 0.94339623, 0.94339623, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.96226415, 0.94339623,
        0.94339623, 0.96226415, 0.96226415, 0.98113208, 0.98113208,
        0.98113208, 0.96226415, 0.94339623, 0.94339623, 0.94339623,
        0.98113208, 0.98113208, 0.98113208, 0.96226415, 0.96226415,
        0.94339623, 0.98113208, 0.94339623]),
 'split3_test_score': array([0.96226415, 0.98113208, 0.96226415, 0.96226415, 0.98113208,
        0.96226415, 0.98113208, 0.98113208, 0.96226415, 0.98113208,
        0.98113208, 0.98113208, 0.96226415, 0.98113208, 0.96226415,
        0.98113208, 0.96226415, 0.98113208, 0.98113208, 0.98113208,
        0.96226415, 0.98113208, 0.96226415, 0.98113208, 0.96226415,
        0.98113208, 0.96226415, 0.98113208, 0.96226415, 0.98113208,
        0.96226415, 0.98113208, 0.98113208, 0.96226415, 0.98113208,
        0.98113208, 0.98113208, 0.96226415, 0.96226415, 0.98113208,
        0.96226415, 0.96226415, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.96226415, 0.98113208]),
 'split4_test_score': array([1.        , 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 1.        , 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        1.        , 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 1.        , 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        1.        , 0.98113208, 0.98113208, 0.98113208, 0.98113208,
        0.98113208, 0.98113208, 0.98113208]),
 'mean_test_score': array([0.97749825, 0.98120196, 0.9661775 , 0.98113208, 0.9661775 ,
        0.9698812 , 0.9661775 , 0.96624738, 0.97365479, 0.98490566,
        0.98490566, 0.98490566, 0.97365479, 0.97742837, 0.95856045,
        0.97358491, 0.97742837, 0.98490566, 0.98120196, 0.98120196,
        0.9698812 , 0.97372467, 0.9661775 , 0.9698812 , 0.98113208,
        0.98497554, 0.97742837, 0.98490566, 0.9698812 , 0.9661775 ,
        0.9698812 , 0.98113208, 0.97742837, 0.97365479, 0.97379455,
        0.97742837, 0.97372467, 0.9698812 , 0.96233403, 0.97365479,
        0.97749825, 0.98113208, 0.98120196, 0.97742837, 0.97735849,
        0.97365479, 0.96995108, 0.96610762]),
 'std_test_score': array([0.01397205, 0.00013976, 0.00748219, 0.01193312, 0.02198139,
        0.0151473 , 0.01408483, 0.01823297, 0.00930129, 0.00754717,
        0.00754717, 0.00754717, 0.01512989, 0.00758332, 0.02207582,
        0.01924158, 0.00758332, 0.00754717, 0.00013976, 0.00013976,
        0.0151473 , 0.00907488, 0.01408483, 0.0151473 , 0.01193312,
        0.00751345, 0.00758332, 0.00754717, 0.0093296 , 0.01408483,
        0.0151473 , 0.01687598, 0.00758332, 0.00930129, 0.01467505,
        0.00758332, 0.00907488, 0.0151473 , 0.01695451, 0.01512989,
        0.01397205, 0.01193312, 0.00013976, 0.00758332, 0.01411946,
        0.01512989, 0.00913281, 0.01854421]),
 'rank_test_score': array([15,  7, 41, 11, 41, 34, 41, 40, 27,  2,  2,  2, 27, 17, 48, 32, 17,
         2,  7,  7, 34, 25, 41, 38, 11,  1, 17,  2, 38, 45, 34, 11, 17, 27,
        24, 22, 25, 34, 47, 27, 15, 11,  7, 17, 23, 27, 33, 46],
       dtype=int32)}

In [20]:
format(grid.best_params_)

"{'bootstrap': True, 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}"

In [22]:
table=pd.DataFrame.from_dict(re)

In [23]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.239909,0.009269,0.017437,0.000991,True,None,sqrt,1,2,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.962963,0.981132,0.981132,0.962264,1.000000,0.977498,0.013972,15
1,0.472004,0.005035,0.027221,0.001851,True,None,sqrt,1,2,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.981481,0.981132,0.981132,0.981132,0.981132,0.981202,0.000140,7
2,0.233856,0.006321,0.016462,0.000497,True,None,sqrt,1,5,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.962963,0.962264,0.962264,0.962264,0.981132,0.966177,0.007482,41
3,0.467798,0.005215,0.025647,0.002038,True,None,sqrt,1,5,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",1.000000,0.981132,0.981132,0.962264,0.981132,0.981132,0.011933,11
4,0.234790,0.009446,0.016021,0.000855,True,None,sqrt,2,2,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.962963,0.981132,0.924528,0.981132,0.981132,0.966177,0.021981,41
5,0.457750,0.007569,0.024397,0.002225,True,None,sqrt,2,2,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.981481,0.981132,0.943396,0.962264,0.981132,0.969881,0.015147,34
6,0.222051,0.002869,0.015807,0.000745,True,None,sqrt,2,5,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.962963,0.943396,0.962264,0.981132,0.981132,0.966177,0.014085,41
7,0.447684,0.005566,0.024697,0.001135,True,None,sqrt,2,5,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.944444,0.981132,0.943396,0.981132,0.981132,0.966247,0.018233,40
8,0.221798,0.002035,0.016427,0.001369,True,None,log2,1,2,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.981481,0.962264,0.981132,0.962264,0.981132,0.973655,0.009301,27
9,0.441932,0.004566,0.026713,0.000983,True,None,log2,1,2,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",1.000000,0.981132,0.981132,0.981132,0.981132,0.984906,0.007547,2
10,0.222250,0.002272,0.016559,0.001626,True,None,log2,1,5,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",1.000000,0.981132,0.981132,0.981132,0.981132,0.984906,0.007547,2
11,0.468147,0.011209,0.024670,0.000603,True,None,log2,1,5,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",1.000000,0.981132,0.981132,0.981132,0.981132,0.984906,0.007547,2
12,0.238994,0.012520,0.015823,0.000493,True,None,log2,2,2,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.981481,0.962264,0.962264,0.962264,1.000000,0.973655,0.015130,27
13,0.461867,0.012169,0.026267,0.002066,True,None,log2,2,2,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.981481,0.981132,0.962264,0.981132,0.981132,0.977428,0.007583,17
14,0.237844,0.002733,0.015744,0.001009,True,None,log2,2,5,100,"{'bootstrap': True, 'max_depth': None, 'max_fe...",0.981481,0.943396,0.924528,0.962264,0.981132,0.958560,0.022076,48
15,0.464523,0.012041,0.026019,0.001419,True,None,log2,2,5,200,"{'bootstrap': True, 'max_depth': None, 'max_fe...",1.000000,0.962264,0.943396,0.981132,0.981132,0.973585,0.019242,32
16,0.229802,0.005173,0.016994,0.001335,True,10,sqrt,1,2,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.981132,0.962264,0.981132,0.977428,0.007583,17
17,0.463619,0.017579,0.024495,0.001266,True,10,sqrt,1,2,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",1.000000,0.981132,0.981132,0.981132,0.981132,0.984906,0.007547,2
18,0.232852,0.012152,0.015550,0.000391,True,10,sqrt,1,5,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.981132,0.981132,0.981132,0.981202,0.000140,7
19,0.446934,0.005775,0.024980,0.000660,True,10,sqrt,1,5,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.981132,0.981132,0.981132,0.981202,0.000140,7
20,0.224163,0.003126,0.015361,0.001628,True,10,sqrt,2,2,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.943396,0.962264,0.981132,0.969881,0.015147,34
21,0.446962,0.007661,0.025142,0.001756,True,10,sqrt,2,2,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.962963,0.981132,0.962264,0.981132,0.981132,0.973725,0.009075,25
22,0.222235,0.002352,0.016834,0.001179,True,10,sqrt,2,5,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.962963,0.981132,0.943396,0.962264,0.981132,0.966177,0.014085,41
23,0.446151,0.001129,0.024834,0.000428,True,10,sqrt,2,5,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.962264,0.943396,0.981132,0.981132,0.969881,0.015147,38
24,0.224981,0.001056,0.015542,0.000945,True,10,log2,1,2,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",1.000000,0.981132,0.981132,0.962264,0.981132,0.981132,0.011933,11
25,0.443509,0.005317,0.025717,0.001231,True,10,log2,1,2,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.981132,0.981132,1.000000,0.984976,0.007513,1
26,0.224821,0.003193,0.015142,0.001130,True,10,log2,1,5,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.981132,0.962264,0.981132,0.977428,0.007583,17
27,0.437863,0.002343,0.026662,0.003222,True,10,log2,1,5,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",1.000000,0.981132,0.981132,0.981132,0.981132,0.984906,0.007547,2
28,0.225811,0.004886,0.016332,0.001552,True,10,log2,2,2,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.962264,0.962264,0.962264,0.981132,0.969881,0.009330,38
29,0.459333,0.021310,0.026091,0.001637,True,10,log2,2,2,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.962963,0.962264,0.943396,0.981132,0.981132,0.966177,0.014085,45
30,0.240108,0.017856,0.015457,0.000496,True,10,log2,2,5,100,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",0.981481,0.981132,0.943396,0.962264,0.981132,0.969881,0.015147,34
31,0.449025,0.014020,0.025842,0.001318,True,10,log2,2,5,200,"{'bootstrap': True, 'max_depth': 10, 'max_feat...",1.000000,0.962264,0.962264,0.981132,1.000000,0.981132,0.016876,11
32,0.227395,0.002757,0.015211,0.000367,True,20,sqrt,1,2,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.981132,0.962264,0.981132,0.981132,0.977428,0.007583,17
33,0.442065,0.004210,0.024198,0.000701,True,20,sqrt,1,2,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.962264,0.981132,0.962264,0.981132,0.973655,0.009301,27
34,0.218559,0.002955,0.018241,0.002518,True,20,sqrt,1,5,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.944444,0.981132,0.981132,0.981132,0.981132,0.973795,0.014675,24
35,0.446015,0.007775,0.025679,0.001851,True,20,sqrt,1,5,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.962264,0.981132,0.981132,0.981132,0.977428,0.007583,22
36,0.222706,0.002794,0.016679,0.000962,True,20,sqrt,2,2,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.962963,0.981132,0.962264,0.981132,0.981132,0.973725,0.009075,25
37,0.446208,0.007027,0.024592,0.000870,True,20,sqrt,2,2,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.981132,0.943396,0.962264,0.981132,0.969881,0.015147,34
38,0.223848,0.006231,0.016349,0.001047,True,20,sqrt,2,5,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.943396,0.943396,0.962264,0.981132,0.962334,0.016955,47
39,0.438776,0.004974,0.025662,0.001240,True,20,sqrt,2,5,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.981132,0.943396,0.981132,0.981132,0.973655,0.015130,27
40,0.225399,0.004160,0.016084,0.000531,True,20,log2,1,2,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.962963,0.981132,0.981132,0.962264,1.000000,0.977498,0.013972,15
41,0.450843,0.009907,0.025417,0.000917,True,20,log2,1,2,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",1.000000,0.981132,0.981132,0.962264,0.981132,0.981132,0.011933,11
42,0.225653,0.003570,0.019347,0.002095,True,20,log2,1,5,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.981132,0.981132,0.981132,0.981132,0.981202,0.000140,7
43,0.456205,0.010929,0.024495,0.000591,True,20,log2,1,5,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.981132,0.962264,0.981132,0.981132,0.977428,0.007583,17
44,0.236041,0.008216,0.015310,0.000488,True,20,log2,2,2,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",1.000000,0.962264,0.962264,0.981132,0.981132,0.977358,0.014119,23
45,0.427999,0.011603,0.021556,0.003654,True,20,log2,2,2,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.981132,0.943396,0.981132,0.981132,0.973655,0.015130,27
46,0.221337,0.001885,0.015163,0.002157,True,20,log2,2,5,100,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.962963,0.962264,0.981132,0.962264,0.981132,0.969951,0.009133,33
47,0.384294,0.013498,0.017112,0.003605,True,20,log2,2,5,200,"{'bootstrap': True, 'max_depth': 20, 'max_feat...",0.981481,0.943396,0.943396,0.981132,0.981132,0.966108,0.018544,46

In [24]:
grid_predictions=grid.predict(x_test)

In [26]:
grid_predictions

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [27]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [28]:
cm

array([[51,  0],
       [ 1, 81]])

In [29]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [31]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133